### PR TITLE
Getters (API) + compile error fix

### PR DESCRIPTION
**Pull request by rokups**
Added four getters to the API:

* bool getEnabled()
* bool getListening()
* bool getEventTracingEnabled()
* bool getLowPriorityEventTracing()

Also i had to change `const char* DAFAULT_ADDRESS` to `#define DAFAULT_ADDRESS` because on my system building vanilla `easy_profiler` failed complaining that multiple `DAFAULT_ADDRESS` symbols being defined.

### CODE REVIEW

**Comment by cas4ey** [comment]
Can you please fix easy_profiler_core/event_trace_win.cpp at line 313 - you have forgotten to put "return"

**Comment by cas4ey** [comment]
Also it would be better to use `std::memory_order_acquire` instead of `std::memory_order_release` when reading atomic value (as I know). Please, correct me if I'm wrong.

**Comment by rokups** [comment]
Sorry about that, not a windows user is my excuse ;)

**Comment by rokups** [comment]
Cleaned up commit. Changed `std::atomic::load()` calls to use `std::memory_order_acquire`. Also changed getter names to start with `is` instead of `get` for bool values because i noticed already existing `EasyEventTracer::isLowPriority()` and decided that is your preferred style in this project. Also added cosnts to these calls for correctness.

**Comment by cas4ey** [comment]
Done! 👍

**Pull request merged**
