### PR TITLE
rename function names related to versions

### PR DESCRIPTION
**Pull request by limingchina**
The current function name is quite generic and it's easy to conflict
with other functions in a project since they're C functions

### CODE REVIEW

**Comment by kevswims** [comment]
The `now()` function also conflicts with other libraries (`libsystemd` in our case). Can renaming that be added to this PR?

**Comment by limingchina** [comment]
> The `now()` function also conflicts with other libraries (`libsystemd` in our case). Can renaming that be added to this PR?

Renamed. However, not sure if the author is actively accepting PRs and merge that to the mainline.

**Comment by yse** [comment]
Hi! There are a few changes that I should merge and make new major release. The fix is good to up a major version, also migrate to [Qt6](https://github.com/yse/easy_profiler/pull/213). Thank you for your contribution. I think I will find time and energy to make project more freshy)

**Comment by yse** [comment]
Great work 🏆 Thank you

I’ll be updating the major version to 3 to stay aligned with semantic versioning.

**Pull request merged**
